version: '3'
services:
  npm:
    build: .
    ports:
      - '1234:1234'
      - '4321:4321'
    volumes:
      - ./:/project
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /project
    entrypoint: npm
    command: start
