version: "3"
services:
  npm:
    build: .
    ports:
      - "1234:1234"
      - "8888:8888"
    volumes:
      - ./:/project
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    working_dir: /project
    entrypoint: npm
    command: start
